"""Per ADR-25 (Option 1): datasette.yaml's own `databases.products.queries`
is read into Datasette's self.config once at startup, so a query
regenerated by `make transform` (or hand-edited) while `make explore` is
already running isn't picked up without a restart. `canned_queries()` is
called fresh on every request (datasette/app.py:855-865), and its return
value is merged over the startup-cached queries via dict.update(), so
re-reading the file here makes on-disk changes win without a restart."""
from datasette import hookimpl
from ruamel.yaml import YAML

_yaml = YAML()


@hookimpl
def canned_queries(database):
    if database != "products":
        return {}
    try:
        with open("datasette.yaml") as f:
            config = _yaml.load(f) or {}
    except FileNotFoundError:
        return {}
    return (
        ((config.get("databases") or {}).get("products") or {}).get("queries") or {}
    )
